style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/werne2j/argocd-vault-plugin
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
